/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.recogidapaquete.interfaces;

import com.mysql.cj.x.protobuf.Mysqlx;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author El cibernetico
 */

public class AdministradorGrafica extends javax.swing.JFrame {

    private int xMove;
    private int yMove;

    
    public AdministradorGrafica() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Icoco Ventana
        this.setIconImage(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/LOGO.png")).getImage());
    }
    
    public void salir(){
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir del Login?","Salir",dialogButton);
        
        if(result==0){
            System.exit(0);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblBarra = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLYC = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblPaquete = new javax.swing.JLabel();
        lblRepaqIcon = new javax.swing.JLabel();
        lblBarraTitulo = new javax.swing.JLabel();
        lblBy = new javax.swing.JLabel();
        jpAddCliente = new javax.swing.JPanel();
        lblAddCliente = new javax.swing.JLabel();
        lblAdministrador = new javax.swing.JLabel();
        lblAmin = new javax.swing.JLabel();
        jpAddReceptor = new javax.swing.JPanel();
        lblAddReceptor = new javax.swing.JLabel();
        jpAddPaquete = new javax.swing.JPanel();
        lblAddPaquete = new javax.swing.JLabel();
        jpGenCorreo = new javax.swing.JPanel();
        lblGenCorreo = new javax.swing.JLabel();
        jpGenReports = new javax.swing.JPanel();
        lblGenReports = new javax.swing.JLabel();
        jpVerPerfil = new javax.swing.JPanel();
        lblVerPerfil = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblRepaq2 = new javax.swing.JLabel();
        jpVerReceptor = new javax.swing.JPanel();
        lblVerReceptor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblIconRepaq = new javax.swing.JLabel();
        lblCopyright = new javax.swing.JLabel();
        lblRepaq = new javax.swing.JLabel();
        lblDesarrollo = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/repaq.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 520));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 118, 255));
        jPanel1.setForeground(new java.awt.Color(0, 118, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/iconClose_normal.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCloseMouseMoved(evt);
            }
        });
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 30, 30));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/minimize_normal.png"))); // NOI18N
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseMoved(evt);
            }
        });
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 30, 30));

        lblBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBarraMouseDragged(evt);
            }
        });
        lblBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBarraMousePressed(evt);
            }
        });
        jPanel1.add(lblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, 740, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 560, 30));

        jPanel2.setBackground(new java.awt.Color(0, 110, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 104, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLYC.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        lblLYC.setForeground(new java.awt.Color(255, 255, 255));
        lblLYC.setText("LYC");
        jPanel2.add(lblLYC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 40, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 89, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 89, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 240, -1));

        lblPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/package.png"))); // NOI18N
        jPanel2.add(lblPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 30, 30));

        lblRepaqIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/repaq1.png"))); // NOI18N
        jPanel2.add(lblRepaqIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lblBarraTitulo.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        lblBarraTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblBarraTitulo.setText("RePAQ");
        jPanel2.add(lblBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 30));

        lblBy.setFont(new java.awt.Font("Open Sans Extrabold", 1, 10)); // NOI18N
        lblBy.setForeground(new java.awt.Color(255, 255, 255));
        lblBy.setText("  By");
        jPanel2.add(lblBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 20, 10));

        jpAddCliente.setBackground(new java.awt.Color(0, 80, 255));
        jpAddCliente.setForeground(new java.awt.Color(0, 80, 255));
        jpAddCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpAddCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpAddClienteMouseMoved(evt);
            }
        });
        jpAddCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpAddClienteMouseExited(evt);
            }
        });
        jpAddCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAddCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/group.png"))); // NOI18N
        lblAddCliente.setText("Agregar Clientes  ");
        lblAddCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAddClienteMouseMoved(evt);
            }
        });
        lblAddCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddClienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddClienteMouseExited(evt);
            }
        });
        jpAddCliente.add(lblAddCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 30));

        jPanel2.add(jpAddCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 30));

        lblAdministrador.setFont(new java.awt.Font("Dosis", 1, 19)); // NOI18N
        lblAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        lblAdministrador.setText("ADMINISTRADOR");
        jPanel2.add(lblAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, 20));

        lblAmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/admin2.png"))); // NOI18N
        lblAmin.setText(".");
        jPanel2.add(lblAmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 34, 60, 70));

        jpAddReceptor.setBackground(new java.awt.Color(0, 80, 255));
        jpAddReceptor.setForeground(new java.awt.Color(0, 80, 255));
        jpAddReceptor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpAddReceptor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpAddReceptorMouseMoved(evt);
            }
        });
        jpAddReceptor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpAddReceptorMouseExited(evt);
            }
        });
        jpAddReceptor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddReceptor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAddReceptor.setForeground(new java.awt.Color(255, 255, 255));
        lblAddReceptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/support1.png"))); // NOI18N
        lblAddReceptor.setText("Agregar Receptor");
        lblAddReceptor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddReceptor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAddReceptorMouseMoved(evt);
            }
        });
        lblAddReceptor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddReceptorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddReceptorMouseExited(evt);
            }
        });
        jpAddReceptor.add(lblAddReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, -1));

        jPanel2.add(jpAddReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 260, 30));

        jpAddPaquete.setBackground(new java.awt.Color(0, 80, 255));
        jpAddPaquete.setForeground(new java.awt.Color(0, 80, 255));
        jpAddPaquete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpAddPaquete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpAddPaqueteMouseMoved(evt);
            }
        });
        jpAddPaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpAddPaqueteMouseExited(evt);
            }
        });
        jpAddPaquete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddPaquete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAddPaquete.setForeground(new java.awt.Color(255, 255, 255));
        lblAddPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/shipping.png"))); // NOI18N
        lblAddPaquete.setText("Agregar Paquetes");
        lblAddPaquete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddPaquete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAddPaqueteMouseMoved(evt);
            }
        });
        lblAddPaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddPaqueteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddPaqueteMouseExited(evt);
            }
        });
        jpAddPaquete.add(lblAddPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, -1));

        jPanel2.add(jpAddPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 260, 30));

        jpGenCorreo.setBackground(new java.awt.Color(0, 80, 255));
        jpGenCorreo.setForeground(new java.awt.Color(0, 80, 255));
        jpGenCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpGenCorreo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpGenCorreoMouseMoved(evt);
            }
        });
        jpGenCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpGenCorreoMouseExited(evt);
            }
        });
        jpGenCorreo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGenCorreo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblGenCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblGenCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/close-envelope.png"))); // NOI18N
        lblGenCorreo.setText("Generar Correo");
        lblGenCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGenCorreo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblGenCorreoMouseMoved(evt);
            }
        });
        lblGenCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenCorreoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGenCorreoMouseExited(evt);
            }
        });
        jpGenCorreo.add(lblGenCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, -1));

        jPanel2.add(jpGenCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 30));

        jpGenReports.setBackground(new java.awt.Color(0, 80, 255));
        jpGenReports.setForeground(new java.awt.Color(0, 80, 255));
        jpGenReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpGenReports.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpGenReportsMouseMoved(evt);
            }
        });
        jpGenReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpGenReportsMouseExited(evt);
            }
        });
        jpGenReports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGenReports.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblGenReports.setForeground(new java.awt.Color(255, 255, 255));
        lblGenReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/report.png"))); // NOI18N
        lblGenReports.setText("Crear Reportes");
        lblGenReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGenReports.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblGenReportsMouseMoved(evt);
            }
        });
        lblGenReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenReportsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGenReportsMouseExited(evt);
            }
        });
        jpGenReports.add(lblGenReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 30));

        jPanel2.add(jpGenReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 30));

        jpVerPerfil.setBackground(new java.awt.Color(0, 80, 255));
        jpVerPerfil.setForeground(new java.awt.Color(0, 80, 255));
        jpVerPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpVerPerfil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpVerPerfilMouseMoved(evt);
            }
        });
        jpVerPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpVerPerfilMouseExited(evt);
            }
        });
        jpVerPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVerPerfil.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVerPerfil.setForeground(new java.awt.Color(255, 255, 255));
        lblVerPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/perfil.png"))); // NOI18N
        lblVerPerfil.setText("Ver Perfil Usuario");
        lblVerPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerPerfil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblVerPerfilMouseMoved(evt);
            }
        });
        lblVerPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerPerfilMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVerPerfilMouseExited(evt);
            }
        });
        jpVerPerfil.add(lblVerPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 30));

        jPanel2.add(jpVerPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 260, 30));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/repaq.png"))); // NOI18N
        jPanel2.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 100, 110));

        lblRepaq2.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        lblRepaq2.setForeground(new java.awt.Color(255, 255, 255));
        lblRepaq2.setText("RePAQ");
        jPanel2.add(lblRepaq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 70, 30));

        jpVerReceptor.setBackground(new java.awt.Color(0, 80, 255));
        jpVerReceptor.setForeground(new java.awt.Color(0, 80, 255));
        jpVerReceptor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpVerReceptor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpVerReceptorMouseMoved(evt);
            }
        });
        jpVerReceptor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpVerReceptorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpVerReceptorMouseExited(evt);
            }
        });
        jpVerReceptor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVerReceptor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVerReceptor.setForeground(new java.awt.Color(255, 255, 255));
        lblVerReceptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/support1.png"))); // NOI18N
        lblVerReceptor.setText("Ver Receptor");
        lblVerReceptor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerReceptor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblVerReceptorMouseMoved(evt);
            }
        });
        lblVerReceptor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerReceptorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVerReceptorMouseExited(evt);
            }
        });
        jpVerReceptor.add(lblVerReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 30));

        jPanel2.add(jpVerReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 520));

        jPanel3.setBackground(new java.awt.Color(109, 157, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconRepaq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/repaq.png"))); // NOI18N
        jPanel3.add(lblIconRepaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 110));

        lblCopyright.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblCopyright.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyright.setText("Copyright © 2018. RePAQ. Todos los derechos Reservados.");
        lblCopyright.setToolTipText("");
        jPanel3.add(lblCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 420, -1));

        lblRepaq.setFont(new java.awt.Font("Open Sans Extrabold", 1, 24)); // NOI18N
        lblRepaq.setForeground(new java.awt.Color(255, 255, 255));
        lblRepaq.setText("RePAQ");
        jPanel3.add(lblRepaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 90, 30));

        lblDesarrollo.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblDesarrollo.setForeground(new java.awt.Color(255, 255, 255));
        lblDesarrollo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesarrollo.setText("<html>RePAQ permitirá  llevar el control de la recogida de paquetes de un listado de clientes, el cual será consultado por el receptor cada vez que llegue una persona en busca de un paquete, puede éste buscar a los clientes por nombre o por apellido. Una vez recogido el paquete, podrá extraerse información estadística acerca de la cantidad de paquetes recogido por día, semana y mes.  </html>");
        lblDesarrollo.setToolTipText("");
        jPanel3.add(lblDesarrollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 480, 150));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 560, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void lblCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseMoved
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/iconClose_Animacion.png")));
    }//GEN-LAST:event_lblCloseMouseMoved
    
    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/iconClose_normal.png")));
    }//GEN-LAST:event_lblCloseMouseExited
    
    private void lblMinimizeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseMoved
        lblMinimize.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/minimizea_animacion.png")));
    }//GEN-LAST:event_lblMinimizeMouseMoved
    
    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/minimize_normal.png")));
    }//GEN-LAST:event_lblMinimizeMouseExited
    
    private void jpAddClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAddClienteMouseMoved
        jpAddCliente.setBackground(new Color(0,0,255));
        jpAddCliente.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpAddClienteMouseMoved
    
    private void lblAddClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddClienteMouseMoved
        jpAddCliente.setBackground(new Color(0,0,255));
        jpAddCliente.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblAddClienteMouseMoved
    
    private void lblAddClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddClienteMouseExited
        jpAddCliente.setBackground(new Color(0,80,255));
        jpAddCliente.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblAddClienteMouseExited
    
    private void jpAddClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAddClienteMouseExited
        jpAddCliente.setBackground(new Color(0,80,255));
        jpAddCliente.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpAddClienteMouseExited
    
    private void lblAddReceptorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddReceptorMouseMoved
        jpAddReceptor.setBackground(new Color(0,0,255));
        jpAddReceptor.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblAddReceptorMouseMoved
    
    private void lblAddReceptorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddReceptorMouseExited
        jpAddReceptor.setBackground(new Color(0,80,255));
        jpAddReceptor.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblAddReceptorMouseExited
    
    private void jpAddReceptorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAddReceptorMouseMoved
        jpAddReceptor.setBackground(new Color(0,0,255));
        jpAddReceptor.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpAddReceptorMouseMoved
    
    private void jpAddReceptorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAddReceptorMouseExited
        jpAddReceptor.setBackground(new Color(0,80,255));
        jpAddReceptor.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpAddReceptorMouseExited
    
    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        salir();
    }//GEN-LAST:event_lblCloseMouseClicked
    
    private void lblAddPaqueteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddPaqueteMouseMoved
        jpAddPaquete.setBackground(new Color(0,0,255));
        jpAddPaquete.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblAddPaqueteMouseMoved
    
    private void lblAddPaqueteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddPaqueteMouseExited
        jpAddPaquete.setBackground(new Color(0,80,255));
        jpAddPaquete.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblAddPaqueteMouseExited
    
    private void jpAddPaqueteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAddPaqueteMouseMoved
        jpAddPaquete.setBackground(new Color(0,0,255));
        jpAddPaquete.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpAddPaqueteMouseMoved
    
    private void jpAddPaqueteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAddPaqueteMouseExited
        jpAddPaquete.setBackground(new Color(0,80,255));
        jpAddPaquete.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpAddPaqueteMouseExited
    
    private void lblGenCorreoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenCorreoMouseMoved
        jpGenCorreo.setBackground(new Color(0,0,255));
        jpGenCorreo.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblGenCorreoMouseMoved
    
    private void lblGenCorreoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenCorreoMouseExited
        jpGenCorreo.setBackground(new Color(0,80,255));
        jpGenCorreo.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblGenCorreoMouseExited
    
    private void jpGenCorreoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGenCorreoMouseMoved
        jpGenCorreo.setBackground(new Color(0,0,255));
        jpGenCorreo.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpGenCorreoMouseMoved
    
    private void jpGenCorreoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGenCorreoMouseExited
        jpGenCorreo.setBackground(new Color(0,80,255));
        jpGenCorreo.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpGenCorreoMouseExited
    
    private void lblGenReportsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenReportsMouseMoved
        jpGenReports.setBackground(new Color(0,0,255));
        jpGenReports.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblGenReportsMouseMoved
    
    private void lblGenReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenReportsMouseExited
        jpGenReports.setBackground(new Color(0,80,255));
        jpGenReports.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblGenReportsMouseExited
    
    private void jpGenReportsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGenReportsMouseMoved
        jpGenReports.setBackground(new Color(0,0,255));
        jpGenReports.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpGenReportsMouseMoved
    
    private void jpGenReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGenReportsMouseExited
        jpGenReports.setBackground(new Color(0,80,255));
        jpGenReports.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpGenReportsMouseExited
    
    private void lblVerPerfilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPerfilMouseMoved
        jpVerPerfil.setBackground(new Color(0,0,255));
        jpVerPerfil.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblVerPerfilMouseMoved
    
    private void lblVerPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPerfilMouseExited
        jpVerPerfil.setBackground(new Color(0,80,255));
        jpVerPerfil.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblVerPerfilMouseExited
    
    private void jpVerPerfilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerPerfilMouseMoved
        jpVerPerfil.setBackground(new Color(0,0,255));
        jpVerPerfil.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpVerPerfilMouseMoved
    
    private void jpVerPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerPerfilMouseExited
        jpVerPerfil.setBackground(new Color(0,80,255));
        jpVerPerfil.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpVerPerfilMouseExited

    private void lblAddClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddClienteMouseClicked
        this.setVisible(false);
        this.dispose();
        AddCliente addCliente = new AddCliente();
        addCliente.setVisible(true);    
    }//GEN-LAST:event_lblAddClienteMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(AdministradorGrafica.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblAddReceptorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddReceptorMouseClicked
        this.setVisible(false);
        this.dispose();
        AddReceptor addReceptor = new AddReceptor();
        addReceptor.setVisible(true);
    }//GEN-LAST:event_lblAddReceptorMouseClicked

    private void lblAddPaqueteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddPaqueteMouseClicked
        this.setVisible(false);
        this.dispose();
        AddPaquete addPaquete = new AddPaquete();
        addPaquete.setVisible(true);
    }//GEN-LAST:event_lblAddPaqueteMouseClicked

    private void lblBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMove, y - yMove);
    }//GEN-LAST:event_lblBarraMouseDragged

    private void lblBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMousePressed
        xMove = evt.getX();
        yMove = evt.getY();
    }//GEN-LAST:event_lblBarraMousePressed

    private void lblGenCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenCorreoMouseClicked
        this.setVisible(false);
        this.dispose();
        GenCorreo genCorreo = new GenCorreo();
        genCorreo.setVisible(true);
    }//GEN-LAST:event_lblGenCorreoMouseClicked

    private void lblGenReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenReportsMouseClicked
        this.setVisible(false);
        this.dispose();
        ReporteRecogidasPaquetes reporteRecogidasPaquetes = new ReporteRecogidasPaquetes();
        reporteRecogidasPaquetes.setVisible(true);
    }//GEN-LAST:event_lblGenReportsMouseClicked

    private void lblVerPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPerfilMouseClicked
        ClienteGrafica clienteGrafica = new ClienteGrafica();
        clienteGrafica.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_lblVerPerfilMouseClicked

    private void lblVerReceptorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerReceptorMouseMoved
        jpVerReceptor.setBackground(new Color(0,0,255));
        jpVerReceptor.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblVerReceptorMouseMoved

    private void lblVerReceptorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerReceptorMouseClicked
        ReceptorGrafica receptorGrafica = new ReceptorGrafica();
        receptorGrafica.setVisible(true);
        receptorGrafica.mostrarDatos();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_lblVerReceptorMouseClicked

    private void lblVerReceptorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerReceptorMouseExited
        jpVerReceptor.setBackground(new Color(0,80,255));
        jpVerReceptor.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblVerReceptorMouseExited

    private void jpVerReceptorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerReceptorMouseMoved
        jpVerReceptor.setBackground(new Color(0,0,255));
        jpVerReceptor.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpVerReceptorMouseMoved

    private void jpVerReceptorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerReceptorMouseExited
        jpVerReceptor.setBackground(new Color(0,80,255));
        jpVerReceptor.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpVerReceptorMouseExited

    private void jpVerReceptorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerReceptorMouseClicked
        ReceptorGrafica receptorGrafica = new ReceptorGrafica();
        receptorGrafica.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jpVerReceptorMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpAddCliente;
    private javax.swing.JPanel jpAddPaquete;
    private javax.swing.JPanel jpAddReceptor;
    private javax.swing.JPanel jpGenCorreo;
    private javax.swing.JPanel jpGenReports;
    private javax.swing.JPanel jpVerPerfil;
    private javax.swing.JPanel jpVerReceptor;
    private javax.swing.JLabel lblAddCliente;
    private javax.swing.JLabel lblAddPaquete;
    private javax.swing.JLabel lblAddReceptor;
    private javax.swing.JLabel lblAdministrador;
    private javax.swing.JLabel lblAmin;
    private javax.swing.JLabel lblBarra;
    private javax.swing.JLabel lblBarraTitulo;
    private javax.swing.JLabel lblBy;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblDesarrollo;
    private javax.swing.JLabel lblGenCorreo;
    private javax.swing.JLabel lblGenReports;
    private javax.swing.JLabel lblIconRepaq;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblLYC;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblPaquete;
    private javax.swing.JLabel lblRepaq;
    private javax.swing.JLabel lblRepaq2;
    private javax.swing.JLabel lblRepaqIcon;
    private javax.swing.JLabel lblVerPerfil;
    private javax.swing.JLabel lblVerReceptor;
    // End of variables declaration//GEN-END:variables
}
