/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.recogidapaquete.interfaces;

import com.recogidapaquete.BD.ConexionMySQL;
import com.recogidapaquete.base.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author El cibernetico
 */

public class ClienteGrafica extends javax.swing.JFrame {

    private int xMove;
    private int yMove;
    private int comprobarUsuarioNulos = 0;
    private ConexionMySQL conexionMySQL;
    ArrayList<Cliente> listaClientes;
    ArrayList<Paquete> listaPaquetes;
    private String user;
    private DefaultTableModel dtm;
    
    public ClienteGrafica() {
        initComponents();
        this.setLocationRelativeTo(null);
        conexionMySQL = ConexionMySQL.getInstance();
        listaClientes = new ArrayList<Cliente>();
        listaPaquetes = new ArrayList<Paquete>();
        
        
        //Icoco Ventana
        this.setIconImage(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/LOGO.png")).getImage());
    }

    public void salir(){
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir del Login?","Salir",dialogButton);
        
        if(result==0){
            System.exit(0);
        }
    }
    
    public void setMediadorConcretoConUsuario(Cliente cliente){
        user = cliente.getUsuario();
    }
    
    public void mostrarClientes(){
        listaClientes = conexionMySQL.verPerfilUsuario(user);

        for (Cliente cliente: listaClientes) {
            lblNombre.setText(cliente.getNombre());
            lblApellido.setText(cliente.getApellido());
            lblDireccion.setText(cliente.getDireccion());
            lblCorreo.setText(cliente.getCorreo());
            lblSexo.setText(cliente.getSexo());
        }
    }
    
    public void mostrarPaquetes(){
        listaPaquetes = conexionMySQL.verPaquetesDePerfilUsuario(user);
        dtm = (DefaultTableModel) jtVerPaquetes.getModel();
        
        dtm.setNumRows(0);
        for (int i=0;i<listaPaquetes.size();i++){
            Object [] row = {listaPaquetes.get(i).getDescripcion(),
            listaPaquetes.get(i).getTipoPaquete(),listaPaquetes.get(i).getEstadoValido(),listaPaquetes.get(i).getUbicacion(),listaPaquetes.get(i).getFecha()};
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblBarra = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLYC = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblPaquete = new javax.swing.JLabel();
        lblRepaqIcon = new javax.swing.JLabel();
        lblBarraTitulo = new javax.swing.JLabel();
        lblBy = new javax.swing.JLabel();
        jpVerPerfil = new javax.swing.JPanel();
        lblVerPerfil = new javax.swing.JLabel();
        lblClienteGrafica = new javax.swing.JLabel();
        lblAmin = new javax.swing.JLabel();
        jpVerPaquetes = new javax.swing.JPanel();
        lblVerPaquetes = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblRepaq2 = new javax.swing.JLabel();
        jpVerPerfilRgresarAdmin = new javax.swing.JPanel();
        lblVerPerfilRgresarAdmin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCopyright = new javax.swing.JLabel();
        lblBienvenidoCliente = new javax.swing.JLabel();
        lblCrearReceptor2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVerPaquetes = new javax.swing.JTable();
        apellido = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/repaq.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 520));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 118, 255));
        jPanel1.setForeground(new java.awt.Color(0, 118, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/iconClose_normal.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCloseMouseMoved(evt);
            }
        });
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 30, 30));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/minimize_normal.png"))); // NOI18N
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseMoved(evt);
            }
        });
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 30, 30));

        lblBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBarraMouseDragged(evt);
            }
        });
        lblBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBarraMousePressed(evt);
            }
        });
        jPanel1.add(lblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, 740, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 560, 30));

        jPanel2.setBackground(new java.awt.Color(0, 110, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 104, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLYC.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        lblLYC.setForeground(new java.awt.Color(255, 255, 255));
        lblLYC.setText("LYC");
        jPanel2.add(lblLYC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 40, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 89, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 89, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 240, -1));

        lblPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/package.png"))); // NOI18N
        jPanel2.add(lblPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 30, 30));

        lblRepaqIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/repaq1.png"))); // NOI18N
        jPanel2.add(lblRepaqIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lblBarraTitulo.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        lblBarraTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblBarraTitulo.setText("RePAQ");
        jPanel2.add(lblBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 30));

        lblBy.setFont(new java.awt.Font("Open Sans Extrabold", 1, 10)); // NOI18N
        lblBy.setForeground(new java.awt.Color(255, 255, 255));
        lblBy.setText("  By");
        jPanel2.add(lblBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 20, 10));

        jpVerPerfil.setBackground(new java.awt.Color(0, 80, 255));
        jpVerPerfil.setForeground(new java.awt.Color(0, 80, 255));
        jpVerPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpVerPerfil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpVerPerfilMouseMoved(evt);
            }
        });
        jpVerPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpVerPerfilMouseExited(evt);
            }
        });
        jpVerPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVerPerfil.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVerPerfil.setForeground(new java.awt.Color(255, 255, 255));
        lblVerPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/search2.png"))); // NOI18N
        lblVerPerfil.setText("Ver Perfil");
        lblVerPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerPerfil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblVerPerfilMouseMoved(evt);
            }
        });
        lblVerPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerPerfilMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVerPerfilMouseExited(evt);
            }
        });
        jpVerPerfil.add(lblVerPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 40));

        jPanel2.add(jpVerPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 260, 40));

        lblClienteGrafica.setFont(new java.awt.Font("Dosis", 1, 19)); // NOI18N
        lblClienteGrafica.setForeground(new java.awt.Color(255, 255, 255));
        lblClienteGrafica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblClienteGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 30));

        lblAmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/usuario.png"))); // NOI18N
        lblAmin.setText(".");
        jPanel2.add(lblAmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 70, 80));

        jpVerPaquetes.setBackground(new java.awt.Color(0, 80, 255));
        jpVerPaquetes.setForeground(new java.awt.Color(0, 80, 255));
        jpVerPaquetes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpVerPaquetes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpVerPaquetesMouseMoved(evt);
            }
        });
        jpVerPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpVerPaquetesMouseExited(evt);
            }
        });
        jpVerPaquetes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVerPaquetes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVerPaquetes.setForeground(new java.awt.Color(255, 255, 255));
        lblVerPaquetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/shipping.png"))); // NOI18N
        lblVerPaquetes.setText("Ver Paquetes");
        lblVerPaquetes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerPaquetes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblVerPaquetesMouseMoved(evt);
            }
        });
        lblVerPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerPaquetesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVerPaquetesMouseExited(evt);
            }
        });
        jpVerPaquetes.add(lblVerPaquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 40));

        jPanel2.add(jpVerPaquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 40));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/repaq.png"))); // NOI18N
        jPanel2.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 100, 110));

        lblRepaq2.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        lblRepaq2.setForeground(new java.awt.Color(255, 255, 255));
        lblRepaq2.setText("RePAQ");
        jPanel2.add(lblRepaq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 70, 30));

        jpVerPerfilRgresarAdmin.setBackground(new java.awt.Color(0, 80, 255));
        jpVerPerfilRgresarAdmin.setForeground(new java.awt.Color(0, 80, 255));
        jpVerPerfilRgresarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpVerPerfilRgresarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpVerPerfilRgresarAdminMouseMoved(evt);
            }
        });
        jpVerPerfilRgresarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpVerPerfilRgresarAdminMouseExited(evt);
            }
        });
        jpVerPerfilRgresarAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVerPerfilRgresarAdmin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVerPerfilRgresarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblVerPerfilRgresarAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/back.png"))); // NOI18N
        lblVerPerfilRgresarAdmin.setText("Regresar a Admin");
        lblVerPerfilRgresarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerPerfilRgresarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblVerPerfilRgresarAdminMouseMoved(evt);
            }
        });
        lblVerPerfilRgresarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerPerfilRgresarAdminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVerPerfilRgresarAdminMouseExited(evt);
            }
        });
        jpVerPerfilRgresarAdmin.add(lblVerPerfilRgresarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 40));

        jPanel2.add(jpVerPerfilRgresarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 260, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 520));

        jPanel3.setBackground(new java.awt.Color(109, 157, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCopyright.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblCopyright.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyright.setText("Copyright © 2018. RePAQ. Todos los derechos Reservados.");
        lblCopyright.setToolTipText("");
        jPanel3.add(lblCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 420, -1));

        lblBienvenidoCliente.setFont(new java.awt.Font("Open Sans Extrabold", 1, 20)); // NOI18N
        lblBienvenidoCliente.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblBienvenidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 250, 30));

        lblCrearReceptor2.setFont(new java.awt.Font("Open Sans Extrabold", 1, 20)); // NOI18N
        lblCrearReceptor2.setForeground(new java.awt.Color(255, 255, 255));
        lblCrearReceptor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCrearReceptor2.setText("Bienvenido a RePAQ.");
        jPanel3.add(lblCrearReceptor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 250, -1));

        jtVerPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripción", "Tipo Paquete", "Estado", "Ubicación", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVerPaquetes.getTableHeader().setResizingAllowed(false);
        jtVerPaquetes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtVerPaquetes);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 540, 100));

        apellido.setFont(new java.awt.Font("Open Sans Extrabold", 1, 15)); // NOI18N
        apellido.setForeground(new java.awt.Color(255, 255, 255));
        apellido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        apellido.setText("Apellido:");
        jPanel3.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 80, -1));

        direccion.setFont(new java.awt.Font("Open Sans Extrabold", 1, 15)); // NOI18N
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        direccion.setText("Dirección:");
        jPanel3.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 80, -1));

        correo.setFont(new java.awt.Font("Open Sans Extrabold", 1, 15)); // NOI18N
        correo.setForeground(new java.awt.Color(255, 255, 255));
        correo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        correo.setText("Correo:");
        jPanel3.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 80, -1));

        sexo.setFont(new java.awt.Font("Open Sans Extrabold", 1, 15)); // NOI18N
        sexo.setForeground(new java.awt.Color(255, 255, 255));
        sexo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sexo.setText("Sexo:");
        jPanel3.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, -1));

        nombre.setFont(new java.awt.Font("Open Sans Extrabold", 1, 15)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombre.setText("Nombre:");
        jPanel3.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 80, -1));

        lblSexo.setFont(new java.awt.Font("Open Sans Extrabold", 1, 15)); // NOI18N
        lblSexo.setForeground(new java.awt.Color(255, 255, 255));
        lblSexo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 270, 20));

        lblNombre.setFont(new java.awt.Font("Open Sans Extrabold", 1, 15)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 270, 20));

        lblApellido.setFont(new java.awt.Font("Open Sans Extrabold", 1, 15)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 270, 20));

        lblDireccion.setFont(new java.awt.Font("Open Sans Extrabold", 1, 15)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 270, 20));

        lblCorreo.setFont(new java.awt.Font("Open Sans Extrabold", 1, 15)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 270, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 560, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void lblCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseMoved
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/iconClose_Animacion.png")));
    }//GEN-LAST:event_lblCloseMouseMoved
    
    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/iconClose_normal.png")));
    }//GEN-LAST:event_lblCloseMouseExited
    
    private void lblMinimizeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseMoved
        lblMinimize.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/minimizea_animacion.png")));
    }//GEN-LAST:event_lblMinimizeMouseMoved
    
    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/minimize_normal.png")));
    }//GEN-LAST:event_lblMinimizeMouseExited
    
    private void jpVerPerfilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerPerfilMouseMoved
        jpVerPerfil.setBackground(new Color(0,0,255));
        jpVerPerfil.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpVerPerfilMouseMoved
    
    private void lblVerPerfilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPerfilMouseMoved
        jpVerPerfil.setBackground(new Color(0,0,255));
        jpVerPerfil.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblVerPerfilMouseMoved
    
    private void lblVerPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPerfilMouseExited
        jpVerPerfil.setBackground(new Color(0,80,255));
        jpVerPerfil.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblVerPerfilMouseExited
    
    private void jpVerPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerPerfilMouseExited
        jpVerPerfil.setBackground(new Color(0,80,255));
        jpVerPerfil.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpVerPerfilMouseExited
    
    private void lblVerPaquetesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPaquetesMouseMoved
        jpVerPaquetes.setBackground(new Color(0,0,255));
        jpVerPaquetes.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblVerPaquetesMouseMoved
    
    private void lblVerPaquetesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPaquetesMouseExited
        jpVerPaquetes.setBackground(new Color(0,80,255));
        jpVerPaquetes.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblVerPaquetesMouseExited
    
    private void jpVerPaquetesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerPaquetesMouseMoved
        jpVerPaquetes.setBackground(new Color(0,0,255));
        jpVerPaquetes.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpVerPaquetesMouseMoved
    
    private void jpVerPaquetesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerPaquetesMouseExited
        jpVerPaquetes.setBackground(new Color(0,80,255));
        jpVerPaquetes.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpVerPaquetesMouseExited
    
    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        salir();
    }//GEN-LAST:event_lblCloseMouseClicked
                                                                
    private void lblVerPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPerfilMouseClicked
        
        if (comprobarUsuarioNulos == 1) {
            this.user = null;
        }
        
        if (user == null) {
            comprobarUsuarioNulos = 1;
            String user = JOptionPane.showInputDialog(null, "Ingrese el usuario del cliente para ver\nsu perfil.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            this.user = user;
        }
        mostrarClientes();
        
    }//GEN-LAST:event_lblVerPerfilMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(ClienteGrafica.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblVerPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPaquetesMouseClicked
        mostrarPaquetes();
    }//GEN-LAST:event_lblVerPaquetesMouseClicked

    private void lblBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMove, y - yMove);
    }//GEN-LAST:event_lblBarraMouseDragged

    private void lblBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMousePressed
        xMove = evt.getX();
        yMove = evt.getY();
    }//GEN-LAST:event_lblBarraMousePressed

    private void lblVerPerfilRgresarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPerfilRgresarAdminMouseMoved
        jpVerPerfilRgresarAdmin.setBackground(new Color(0,0,255));
        jpVerPerfilRgresarAdmin.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblVerPerfilRgresarAdminMouseMoved

    private void lblVerPerfilRgresarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPerfilRgresarAdminMouseClicked
        AdministradorGrafica administrador = new AdministradorGrafica();
        administrador.setVisible(true);
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_lblVerPerfilRgresarAdminMouseClicked

    private void lblVerPerfilRgresarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPerfilRgresarAdminMouseExited
        jpVerPerfilRgresarAdmin.setBackground(new Color(0,80,255));
        jpVerPerfilRgresarAdmin.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblVerPerfilRgresarAdminMouseExited

    private void jpVerPerfilRgresarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerPerfilRgresarAdminMouseMoved
        jpVerPerfilRgresarAdmin.setBackground(new Color(0,0,255));
        jpVerPerfilRgresarAdmin.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpVerPerfilRgresarAdminMouseMoved

    private void jpVerPerfilRgresarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerPerfilRgresarAdminMouseExited
        jpVerPerfilRgresarAdmin.setBackground(new Color(0,80,255));
        jpVerPerfilRgresarAdmin.setForeground(new Color(0,80,255));    }//GEN-LAST:event_jpVerPerfilRgresarAdminMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpVerPaquetes;
    private javax.swing.JPanel jpVerPerfil;
    public javax.swing.JPanel jpVerPerfilRgresarAdmin;
    private javax.swing.JTable jtVerPaquetes;
    private javax.swing.JLabel lblAmin;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBarra;
    private javax.swing.JLabel lblBarraTitulo;
    private javax.swing.JLabel lblBienvenidoCliente;
    private javax.swing.JLabel lblBy;
    private javax.swing.JLabel lblClienteGrafica;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCrearReceptor2;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblLYC;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPaquete;
    private javax.swing.JLabel lblRepaq2;
    private javax.swing.JLabel lblRepaqIcon;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblVerPaquetes;
    private javax.swing.JLabel lblVerPerfil;
    public javax.swing.JLabel lblVerPerfilRgresarAdmin;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel sexo;
    // End of variables declaration//GEN-END:variables
}
