/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.recogidapaquete.interfaces;

import com.recogidapaquete.BD.ConexionMySQL;
import com.recogidapaquete.base.Entregado;
import com.recogidapaquete.base.Paquete;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author El cibernetico
 */

public class ReceptorGrafica extends javax.swing.JFrame {

    private int xMove;
    private int yMove;
    private ConexionMySQL conexionMySQL = ConexionMySQL.getInstance();
    private ArrayList<Paquete>listadoPaquete = new ArrayList<Paquete>();
    private DefaultTableModel dtm;
    
    public ReceptorGrafica() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Icoco Ventana
        this.setIconImage(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/LOGO.png")).getImage());
//        mostrarDatos();
    }
    
    public void salir(){
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir del Login?","Salir",dialogButton);
        
        if(result==0){
            System.exit(0);
        }
    }
    
    public void mostrarDatos(){
        listadoPaquete = conexionMySQL.getPaqueteDisponible();
        dtm= (DefaultTableModel) jtPaquetes.getModel();
        dtm.setNumRows(0);
        for (int i=0;i<listadoPaquete.size();i++){
            Object [] row = {listadoPaquete.get(i).getId_paquete(),listadoPaquete.get(i).getId_cliente(),listadoPaquete.get(i).getDescripcion(),
            listadoPaquete.get(i).getTipoPaquete(),listadoPaquete.get(i).getEstadoValido(),listadoPaquete.get(i).getUbicacion(),listadoPaquete.get(i).getFecha()};
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblBarra = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLYC = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblPaquete = new javax.swing.JLabel();
        lblRepaqIcon = new javax.swing.JLabel();
        lblBarraTitulo = new javax.swing.JLabel();
        lblBy = new javax.swing.JLabel();
        jpAddCliente = new javax.swing.JPanel();
        lblAddCliente = new javax.swing.JLabel();
        lblAdministrador = new javax.swing.JLabel();
        lblAmin = new javax.swing.JLabel();
        jpAddReceptor = new javax.swing.JPanel();
        lblAddReceptor = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblRepaq2 = new javax.swing.JLabel();
        jpRegresarAdministrador = new javax.swing.JPanel();
        lblRegresarAdministrador = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCopyright = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPaquetes = new javax.swing.JTable();
        lblCrearReceptor1 = new javax.swing.JLabel();
        jpEstado = new javax.swing.JPanel();
        rbtnEntregado = new javax.swing.JRadioButton();
        lblEstadoPaquete = new javax.swing.JLabel();
        jpCambiarEstado = new javax.swing.JPanel();
        lblCambiarEstado = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/repaq.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 520));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 118, 255));
        jPanel1.setForeground(new java.awt.Color(0, 118, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/iconClose_normal.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCloseMouseMoved(evt);
            }
        });
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 30, 30));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/minimize_normal.png"))); // NOI18N
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseMoved(evt);
            }
        });
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 30, 30));

        lblBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBarraMouseDragged(evt);
            }
        });
        lblBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBarraMousePressed(evt);
            }
        });
        jPanel1.add(lblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, 740, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 560, 30));

        jPanel2.setBackground(new java.awt.Color(0, 110, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 104, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLYC.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        lblLYC.setForeground(new java.awt.Color(255, 255, 255));
        lblLYC.setText("LYC");
        jPanel2.add(lblLYC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 40, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 89, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 89, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 240, -1));

        lblPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/package.png"))); // NOI18N
        jPanel2.add(lblPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 30, 30));

        lblRepaqIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/repaq1.png"))); // NOI18N
        jPanel2.add(lblRepaqIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lblBarraTitulo.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        lblBarraTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblBarraTitulo.setText("RePAQ");
        jPanel2.add(lblBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 30));

        lblBy.setFont(new java.awt.Font("Open Sans Extrabold", 1, 10)); // NOI18N
        lblBy.setForeground(new java.awt.Color(255, 255, 255));
        lblBy.setText("  By");
        jPanel2.add(lblBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 20, 10));

        jpAddCliente.setBackground(new java.awt.Color(0, 80, 255));
        jpAddCliente.setForeground(new java.awt.Color(0, 80, 255));
        jpAddCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpAddCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpAddClienteMouseMoved(evt);
            }
        });
        jpAddCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpAddClienteMouseExited(evt);
            }
        });
        jpAddCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAddCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/group.png"))); // NOI18N
        lblAddCliente.setText("Buscar clientes");
        lblAddCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAddClienteMouseMoved(evt);
            }
        });
        lblAddCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddClienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddClienteMouseExited(evt);
            }
        });
        jpAddCliente.add(lblAddCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 40));

        jPanel2.add(jpAddCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 260, 40));

        lblAdministrador.setFont(new java.awt.Font("Dosis", 1, 19)); // NOI18N
        lblAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        lblAdministrador.setText("RECEPTOR");
        jPanel2.add(lblAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 100, 20));

        lblAmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/receptorReceptor.png"))); // NOI18N
        lblAmin.setText(".");
        jPanel2.add(lblAmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 60, 60));

        jpAddReceptor.setBackground(new java.awt.Color(0, 80, 255));
        jpAddReceptor.setForeground(new java.awt.Color(0, 80, 255));
        jpAddReceptor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpAddReceptor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpAddReceptorMouseMoved(evt);
            }
        });
        jpAddReceptor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpAddReceptorMouseExited(evt);
            }
        });
        jpAddReceptor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddReceptor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAddReceptor.setForeground(new java.awt.Color(255, 255, 255));
        lblAddReceptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/support1.png"))); // NOI18N
        lblAddReceptor.setText("Buscar por Estado");
        lblAddReceptor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddReceptor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAddReceptorMouseMoved(evt);
            }
        });
        lblAddReceptor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddReceptorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddReceptorMouseExited(evt);
            }
        });
        jpAddReceptor.add(lblAddReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 40));

        jPanel2.add(jpAddReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 40));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/repaq.png"))); // NOI18N
        jPanel2.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 100, 110));

        lblRepaq2.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        lblRepaq2.setForeground(new java.awt.Color(255, 255, 255));
        lblRepaq2.setText("RePAQ");
        jPanel2.add(lblRepaq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 70, 30));

        jpRegresarAdministrador.setBackground(new java.awt.Color(0, 80, 255));
        jpRegresarAdministrador.setForeground(new java.awt.Color(0, 80, 255));
        jpRegresarAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpRegresarAdministrador.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpRegresarAdministradorMouseMoved(evt);
            }
        });
        jpRegresarAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpRegresarAdministradorMouseExited(evt);
            }
        });
        jpRegresarAdministrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegresarAdministrador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRegresarAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        lblRegresarAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/back.png"))); // NOI18N
        lblRegresarAdministrador.setText("Regresar a Admin");
        lblRegresarAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegresarAdministrador.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblRegresarAdministradorMouseMoved(evt);
            }
        });
        lblRegresarAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarAdministradorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegresarAdministradorMouseExited(evt);
            }
        });
        jpRegresarAdministrador.add(lblRegresarAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 40));

        jPanel2.add(jpRegresarAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 260, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 520));

        jPanel3.setBackground(new java.awt.Color(109, 157, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCopyright.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblCopyright.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyright.setText("Copyright © 2018. RePAQ. Todos los derechos Reservados.");
        lblCopyright.setToolTipText("");
        jPanel3.add(lblCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 420, -1));

        jtPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Paquete", "Usuario", "Descripción", "Tipo Paquete", "Estado", "Ubicación", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPaquetes.getTableHeader().setResizingAllowed(false);
        jtPaquetes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtPaquetes);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 540, 250));

        lblCrearReceptor1.setFont(new java.awt.Font("Open Sans Extrabold", 1, 20)); // NOI18N
        lblCrearReceptor1.setForeground(new java.awt.Color(255, 255, 255));
        lblCrearReceptor1.setText("Paquetes Disponibles para Hoy");
        jPanel3.add(lblCrearReceptor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jpEstado.setBackground(new java.awt.Color(109, 151, 255));
        jpEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 130, 255)));
        jpEstado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtnEntregado.setText("Entregado");
        jpEstado.add(rbtnEntregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        lblEstadoPaquete.setFont(new java.awt.Font("Open Sans Extrabold", 1, 20)); // NOI18N
        lblEstadoPaquete.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoPaquete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoPaquete.setText("Estado Paquete:");
        jpEstado.add(lblEstadoPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 20));

        jPanel3.add(jpEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 230, 90));

        jpCambiarEstado.setBackground(new java.awt.Color(0, 80, 255));
        jpCambiarEstado.setForeground(new java.awt.Color(0, 80, 255));
        jpCambiarEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpCambiarEstado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpCambiarEstadoMouseMoved(evt);
            }
        });
        jpCambiarEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpCambiarEstadoMouseExited(evt);
            }
        });
        jpCambiarEstado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCambiarEstado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCambiarEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblCambiarEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recogidapaquete/images/gen.png"))); // NOI18N
        lblCambiarEstado.setText("Cambiar Estado");
        lblCambiarEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCambiarEstado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCambiarEstadoMouseMoved(evt);
            }
        });
        lblCambiarEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCambiarEstadoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCambiarEstadoMouseExited(evt);
            }
        });
        jpCambiarEstado.add(lblCambiarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 40));

        jPanel3.add(jpCambiarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 200, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 560, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void lblCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseMoved
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/iconClose_Animacion.png")));
    }//GEN-LAST:event_lblCloseMouseMoved
    
    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/iconClose_normal.png")));
    }//GEN-LAST:event_lblCloseMouseExited
    
    private void lblMinimizeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseMoved
        lblMinimize.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/minimizea_animacion.png")));
    }//GEN-LAST:event_lblMinimizeMouseMoved
    
    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setIcon(new ImageIcon(getClass().getResource("/com/recogidapaquete/images/minimize_normal.png")));
    }//GEN-LAST:event_lblMinimizeMouseExited
    
    private void jpAddClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAddClienteMouseMoved
        jpAddCliente.setBackground(new Color(0,0,255));
        jpAddCliente.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpAddClienteMouseMoved
    
    private void lblAddClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddClienteMouseMoved
        jpAddCliente.setBackground(new Color(0,0,255));
        jpAddCliente.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblAddClienteMouseMoved
    
    private void lblAddClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddClienteMouseExited
        jpAddCliente.setBackground(new Color(0,80,255));
        jpAddCliente.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblAddClienteMouseExited
    
    private void jpAddClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAddClienteMouseExited
        jpAddCliente.setBackground(new Color(0,80,255));
        jpAddCliente.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpAddClienteMouseExited
    
    private void lblAddReceptorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddReceptorMouseMoved
        jpAddReceptor.setBackground(new Color(0,0,255));
        jpAddReceptor.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblAddReceptorMouseMoved
    
    private void lblAddReceptorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddReceptorMouseExited
        jpAddReceptor.setBackground(new Color(0,80,255));
        jpAddReceptor.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblAddReceptorMouseExited
    
    private void jpAddReceptorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAddReceptorMouseMoved
        jpAddReceptor.setBackground(new Color(0,0,255));
        jpAddReceptor.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpAddReceptorMouseMoved
    
    private void jpAddReceptorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAddReceptorMouseExited
        jpAddReceptor.setBackground(new Color(0,80,255));
        jpAddReceptor.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpAddReceptorMouseExited
    
    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        salir();
    }//GEN-LAST:event_lblCloseMouseClicked
                                                                
    private void lblAddClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddClienteMouseClicked
        BuscarClientes buscarClientes = new BuscarClientes();
        buscarClientes.setVisible(true);    
    }//GEN-LAST:event_lblAddClienteMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(ReceptorGrafica.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblAddReceptorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddReceptorMouseClicked
        BuscarPaquetePorEstados buscarPaquetePorEstados = new BuscarPaquetePorEstados();
        buscarPaquetePorEstados.setVisible(true);
    }//GEN-LAST:event_lblAddReceptorMouseClicked

    private void lblBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMove, y - yMove);
    }//GEN-LAST:event_lblBarraMouseDragged

    private void lblBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMousePressed
        xMove = evt.getX();
        yMove = evt.getY();
    }//GEN-LAST:event_lblBarraMousePressed

    private void lblCambiarEstadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarEstadoMouseMoved
        jpCambiarEstado.setBackground(new Color(0,0,255));
        jpCambiarEstado.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblCambiarEstadoMouseMoved

    private void lblCambiarEstadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarEstadoMouseExited
        jpCambiarEstado.setBackground(new Color(0,80,255));
        jpCambiarEstado.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblCambiarEstadoMouseExited

    private void jpCambiarEstadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCambiarEstadoMouseMoved
        jpCambiarEstado.setBackground(new Color(0,0,255));
        jpCambiarEstado.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpCambiarEstadoMouseMoved

    private void jpCambiarEstadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCambiarEstadoMouseExited
        jpCambiarEstado.setBackground(new Color(0,80,255));
        jpCambiarEstado.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpCambiarEstadoMouseExited

    private void lblCambiarEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarEstadoMouseClicked
        try {
            int fsel = jtPaquetes.getSelectedRow();
            String id_paquete = String.valueOf(jtPaquetes.getValueAt(fsel, 0).toString());

            Entregado entregado = new Entregado();
            Paquete paquete = new Paquete();
            
            if (rbtnEntregado.isSelected() == true) {
                paquete.setEstado(entregado);
                paquete.ejecutarAccion();
                conexionMySQL.cambiarEstado(paquete.getEstadoValido(), id_paquete);
                mostrarDatos();
            } else {
                JOptionPane.showMessageDialog(null, "Compruebe que 'Estado' fue selecionado.\n", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cambiar estado.\n"+e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_lblCambiarEstadoMouseClicked

    private void lblRegresarAdministradorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarAdministradorMouseMoved
        jpRegresarAdministrador.setBackground(new Color(0,0,255));
        jpRegresarAdministrador.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_lblRegresarAdministradorMouseMoved

    private void lblRegresarAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarAdministradorMouseClicked
        AdministradorGrafica administradorGrafica = new AdministradorGrafica();
        administradorGrafica.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_lblRegresarAdministradorMouseClicked

    private void lblRegresarAdministradorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarAdministradorMouseExited
        jpRegresarAdministrador.setBackground(new Color(0,80,255));
        jpRegresarAdministrador.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_lblRegresarAdministradorMouseExited

    private void jpRegresarAdministradorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpRegresarAdministradorMouseMoved
        jpRegresarAdministrador.setBackground(new Color(0,0,255));
        jpRegresarAdministrador.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jpRegresarAdministradorMouseMoved

    private void jpRegresarAdministradorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpRegresarAdministradorMouseExited
        jpRegresarAdministrador.setBackground(new Color(0,80,255));
        jpRegresarAdministrador.setForeground(new Color(0,80,255));
    }//GEN-LAST:event_jpRegresarAdministradorMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptorGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptorGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptorGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptorGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptorGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpAddCliente;
    private javax.swing.JPanel jpAddReceptor;
    private javax.swing.JPanel jpCambiarEstado;
    private javax.swing.JPanel jpEstado;
    public javax.swing.JPanel jpRegresarAdministrador;
    private javax.swing.JTable jtPaquetes;
    private javax.swing.JLabel lblAddCliente;
    private javax.swing.JLabel lblAddReceptor;
    private javax.swing.JLabel lblAdministrador;
    private javax.swing.JLabel lblAmin;
    private javax.swing.JLabel lblBarra;
    private javax.swing.JLabel lblBarraTitulo;
    private javax.swing.JLabel lblBy;
    private javax.swing.JLabel lblCambiarEstado;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblCrearReceptor1;
    private javax.swing.JLabel lblEstadoPaquete;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblLYC;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblPaquete;
    public javax.swing.JLabel lblRegresarAdministrador;
    private javax.swing.JLabel lblRepaq2;
    private javax.swing.JLabel lblRepaqIcon;
    private javax.swing.JRadioButton rbtnEntregado;
    // End of variables declaration//GEN-END:variables
}
